// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scheduley.Infrastructure.DbContexts;

#nullable disable

namespace Scheduley.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Scheduley.Core.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MessageType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Sent")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MessageID");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");

                    b.HasDiscriminator<int>("MessageType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Scheduley.Core.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BucketName")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefreshToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = new Guid("7e91312b-5175-47cf-ab07-8f293772feed"),
                            BucketName = new Guid("0a04b8fb-7416-4bfc-8ef0-7a505fe803a1"),
                            CreatedAt = new DateTime(2025, 4, 14, 3, 58, 8, 478, DateTimeKind.Utc).AddTicks(2445),
                            Email = "ahmad.mhfz1412@gmail.com",
                            LastLogin = new DateTime(2025, 4, 14, 3, 58, 8, 478, DateTimeKind.Utc).AddTicks(2448),
                            Name = "Ahmad Mahfouz",
                            UserRole = 0
                        },
                        new
                        {
                            UserID = new Guid("4bf68c7d-f166-4dc0-92cd-9ae4c519da61"),
                            BucketName = new Guid("bb5c4df4-1b56-4f30-9d45-ec7a57743ce6"),
                            CreatedAt = new DateTime(2025, 4, 14, 3, 58, 8, 478, DateTimeKind.Utc).AddTicks(2476),
                            Email = "thecityhunterhd@gmail.com",
                            LastLogin = new DateTime(2025, 4, 14, 3, 58, 8, 478, DateTimeKind.Utc).AddTicks(2476),
                            Name = "Molly",
                            UserRole = 0
                        });
                });

            modelBuilder.Entity("Scheduley.Core.Domain.Entities.AppMessage", b =>
                {
                    b.HasBaseType("Scheduley.Core.Domain.Entities.Message");

                    b.Property<Guid>("RecipientID")
                        .HasColumnType("uniqueidentifier");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Scheduley.Core.Domain.Entities.WhatsAppMessage", b =>
                {
                    b.HasBaseType("Scheduley.Core.Domain.Entities.Message");

                    b.Property<string>("RecipientPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Scheduley.Core.Domain.Entities.Message", b =>
                {
                    b.HasOne("Scheduley.Core.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
